export const REAL_ESTATE_MODULES = [
  {
    slug: "neighborhood",
    path: "/re/neighborhood",
    label: "Neighborhood Report",
    description: "Create a client-facing neighborhood market report.",
    fields: [
      { name: "neighborhood", label: "Neighborhood / Area", required: true },
      { name: "location", label: "City / ZIP", required: true },
      { name: "property_type", label: "Property Type Focus", placeholder: "Single family residential" },
      { name: "price_range", label: "Price Range in Area", placeholder: "$500K-$700K" },
      { name: "agent_notes", label: "Agent Notes", type: "textarea", rows: 3 },
    ],
  },
  {
    slug: "appointment",
    path: "/re/appointment",
    label: "Listing Appointment",
    description: "Build listing presentation talking points and objection responses.",
    fields: [
      { name: "address", label: "Property Address", required: true },
      { name: "specs", label: "Bedrooms / Baths / Sqft", required: true },
      { name: "value_range", label: "Estimated Value Range" },
      { name: "seller_situation", label: "Seller Situation", type: "textarea", rows: 2 },
      { name: "challenges", label: "Known Challenges", type: "textarea", rows: 2 },
      { name: "notes", label: "Agent Notes", type: "textarea", rows: 3 },
    ],
  },
  {
    slug: "competitive",
    path: "/re/competitive",
    label: "Competitive Analysis",
    description: "Compare a subject listing against active competition.",
    fields: [
      { name: "address", label: "Subject Property", required: true },
      { name: "specs", label: "Subject Specs", required: true },
      { name: "list_price", label: "List Price" },
      { name: "features", label: "Key Features", type: "textarea", rows: 3 },
      { name: "competitors", label: "Competing Active Listings", type: "textarea", rows: 5, placeholder: "One listing per line with price, specs, DOM, and notes" },
      { name: "market_notes", label: "Market Context", type: "textarea", rows: 2 },
    ],
  },
  {
    slug: "timeline",
    path: "/re/timeline",
    label: "Transaction Timeline",
    description: "Generate milestone emails for buyers or sellers under contract.",
    fields: [
      { name: "transaction_type", label: "Transaction Type", type: "select", options: [{ value: "purchase", label: "Purchase" }, { value: "sale", label: "Sale" }], defaultValue: "purchase" },
      { name: "client_type", label: "Client Type", type: "select", options: [{ value: "buyer", label: "Buyer" }, { value: "seller", label: "Seller" }], defaultValue: "buyer" },
      { name: "client_name", label: "Client Name", required: true },
      { name: "address", label: "Property Address", required: true },
      { name: "contract_date", label: "Contract Date", type: "date" },
      { name: "inspection_end", label: "Inspection Period Ends", type: "date" },
      { name: "appraisal_date", label: "Appraisal Deadline", type: "date" },
      { name: "loan_commitment", label: "Loan Commitment", type: "date" },
      { name: "walkthrough_date", label: "Final Walkthrough", type: "date" },
      { name: "closing_date", label: "Closing Date", type: "date", required: true },
    ],
  },
  {
    slug: "seller-update",
    path: "/re/seller-update",
    label: "Seller Update",
    description: "Write a weekly listing update email for sellers.",
    fields: [
      { name: "seller_name", label: "Seller Name", required: true },
      { name: "address", label: "Property Address", required: true },
      { name: "dom", label: "Days on Market", type: "number" },
      { name: "week_number", label: "Week Number" },
      { name: "showing_count", label: "Showings This Week", type: "number" },
      { name: "feedback", label: "Buyer Feedback", type: "textarea", rows: 4 },
      { name: "price_discussion", label: "Price Discussion Needed", type: "select", options: [{ value: "No", label: "No" }, { value: "Yes", label: "Yes" }], defaultValue: "No" },
      { name: "market_notes", label: "Market Notes", type: "textarea", rows: 2 },
      { name: "agent_actions", label: "Agent Action Items", type: "textarea", rows: 2 },
    ],
  },
  {
    slug: "buyer-consult",
    path: "/re/buyer-consult",
    label: "Buyer Consultation",
    description: "Turn buyer consultation notes into a needs analysis.",
    fields: [
      { name: "buyer_names", label: "Buyer Name(s)", required: true },
      { name: "date", label: "Consultation Date", type: "date" },
      { name: "pre_approved", label: "Pre-Approved", type: "select", options: [{ value: "Unknown", label: "Unknown" }, { value: "Yes", label: "Yes" }, { value: "No", label: "No" }], defaultValue: "Unknown" },
      { name: "budget", label: "Budget Range", required: true },
      { name: "down_payment", label: "Down Payment" },
      { name: "target_areas", label: "Target Areas", type: "textarea", rows: 2 },
      { name: "must_haves", label: "Must-Haves", type: "textarea", rows: 3 },
      { name: "nice_to_haves", label: "Nice-to-Haves", type: "textarea", rows: 2 },
      { name: "deal_breakers", label: "Deal-Breakers", type: "textarea", rows: 2 },
      { name: "timeline", label: "Timeline to Buy" },
      { name: "motivation", label: "Motivation", type: "textarea", rows: 2 },
      { name: "current_situation", label: "Current Situation", type: "textarea", rows: 2 },
      { name: "agent_notes", label: "Private Agent Notes", type: "textarea", rows: 3 },
    ],
  },
  {
    slug: "offer-letter",
    path: "/re/offer-letter",
    label: "Offer Letter",
    description: "Draft a personal buyer-to-seller letter.",
    fields: [
      { name: "buyer_names", label: "Buyer Name(s)", required: true },
      { name: "buyer_situation", label: "Buyer Situation", type: "textarea", rows: 2 },
      { name: "home_highlights", label: "What They Loved About the Home", type: "textarea", rows: 3, required: true },
      { name: "buyer_story", label: "Buyer Story", type: "textarea", rows: 4, required: true },
      { name: "tone", label: "Tone", defaultValue: "Warm and sincere" },
      { name: "extra_details", label: "Additional Personal Details", type: "textarea", rows: 2 },
    ],
  },
  {
    slug: "expired-outreach",
    path: "/re/expired-outreach",
    label: "Expired / FSBO",
    description: "Create a five-touch expired listing or FSBO outreach sequence.",
    fields: [
      { name: "lead_type", label: "Lead Type", type: "select", options: [{ value: "Expired listing", label: "Expired Listing" }, { value: "FSBO", label: "FSBO" }], defaultValue: "Expired listing" },
      { name: "owner_name", label: "Owner Name" },
      { name: "address", label: "Property Address", required: true },
      { name: "days", label: "Days Expired / FSBO" },
      { name: "original_price", label: "Original List Price" },
      { name: "reason", label: "Known Reason", type: "textarea", rows: 2 },
      { name: "differentiator", label: "Agent Differentiator", type: "textarea", rows: 2 },
    ],
  },
  {
    slug: "soi-campaign",
    path: "/re/soi-campaign",
    label: "SOI Campaign",
    description: "Generate relationship-focused sphere emails by segment.",
    fields: [
      { name: "segments", label: "Segments", type: "textarea", rows: 4, placeholder: "Past clients: homeowners from last 3 years\nReferral partners: lenders, attorneys" },
      { name: "context", label: "Season / Context" },
      { name: "value_offer", label: "Value to Offer" },
      { name: "cta", label: "Call to Action" },
    ],
  },
  {
    slug: "just-listed",
    path: "/re/just-listed",
    label: "Just Listed / Sold",
    description: "Create a full announcement suite for a listing or sale.",
    fields: [
      { name: "announcement_type", label: "Announcement Type", type: "select", options: [{ value: "Just Listed", label: "Just Listed" }, { value: "Just Sold", label: "Just Sold" }], defaultValue: "Just Listed" },
      { name: "address", label: "Property Address", required: true },
      { name: "price", label: "Price" },
      { name: "specs", label: "Key Stats" },
      { name: "headline_feature", label: "Headline Feature" },
      { name: "ig_handle", label: "Instagram Handle" },
      { name: "open_house", label: "Open House Info" },
    ],
  },
  {
    slug: "open-house-followup",
    path: "/re/open-house-followup",
    label: "Open House Follow-Up",
    description: "Write personalized follow-up emails for open house visitors.",
    fields: [
      { name: "address", label: "Property Address", required: true },
      { name: "date", label: "Open House Date", type: "date" },
      { name: "visitors", label: "Visitors and Notes", type: "textarea", rows: 6, placeholder: "Jane, jane@email.com: liked kitchen, worried about commute" },
    ],
  },
  {
    slug: "virtual-staging",
    path: "/re/virtual-staging",
    label: "Virtual Staging",
    description: "Create room-by-room staging recommendations and buyer vision copy.",
    fields: [
      { name: "style", label: "Property Style" },
      { name: "target_buyer", label: "Target Buyer" },
      { name: "price", label: "Price Point" },
      { name: "rooms", label: "Rooms", type: "textarea", rows: 6, placeholder: "Living room: 18x20, empty, fireplace\nPrimary bedroom: needs warmth" },
    ],
  },
  {
    slug: "property-faq",
    path: "/re/property-faq",
    label: "Property FAQ",
    description: "Generate a showing and open house FAQ document.",
    fields: [
      { name: "address", label: "Property Address", required: true },
      { name: "property_details", label: "Property Details", type: "textarea", rows: 4 },
      { name: "hoa", label: "HOA" },
      { name: "hoa_fee", label: "HOA Monthly Fee" },
      { name: "hoa_covers", label: "What HOA Covers" },
      { name: "schools", label: "School District" },
      { name: "flood_zone", label: "Flood Zone" },
      { name: "utilities", label: "Utilities" },
      { name: "updates", label: "Recent Updates", type: "textarea", rows: 2 },
      { name: "closing_pref", label: "Seller Closing Timeline" },
      { name: "inclusions", label: "Inclusions" },
      { name: "exclusions", label: "Exclusions" },
      { name: "showing_instructions", label: "Showing Instructions" },
      { name: "notes", label: "Additional Notes", type: "textarea", rows: 2 },
    ],
  },
  {
    slug: "price-reduction",
    path: "/re/price-reduction",
    label: "Price Reduction",
    description: "Prepare a data-informed price reduction recommendation memo.",
    fields: [
      { name: "seller_name", label: "Seller Name", required: true },
      { name: "address", label: "Property Address", required: true },
      { name: "current_price", label: "Current List Price", required: true },
      { name: "dom", label: "Days on Market", type: "number" },
      { name: "showings", label: "Showings to Date", type: "number" },
      { name: "offers", label: "Offers Received" },
      { name: "feedback", label: "Buyer Feedback Themes", type: "textarea", rows: 4 },
      { name: "recommended_price", label: "Recommended New Price" },
      { name: "competition", label: "Competing Listings", type: "textarea", rows: 3 },
      { name: "market_trend", label: "Market Trend" },
    ],
  },
  {
    slug: "business-plan",
    path: "/re/business-plan",
    label: "Business Plan",
    description: "Build an annual agent business plan and review.",
    fields: [
      { name: "agent_name", label: "Agent Name", required: true },
      { name: "years", label: "Years in Business" },
      { name: "last_closings", label: "Last Year Closings", type: "number" },
      { name: "last_gci", label: "Last Year GCI" },
      { name: "lead_sources", label: "Top Lead Sources", type: "textarea", rows: 2 },
      { name: "goal_closings", label: "Goal Closings Next Year", type: "number" },
      { name: "goal_gci", label: "Goal GCI Next Year" },
      { name: "avg_commission", label: "Average Commission" },
      { name: "team_size", label: "Team Size" },
      { name: "challenge", label: "Biggest Challenge Last Year", type: "textarea", rows: 2 },
      { name: "focus", label: "Focus Area for Growth", type: "textarea", rows: 2 },
    ],
  },
  {
    slug: "bio",
    path: "/re/bio",
    label: "Agent Bio",
    description: "Write agent bios in long, short, and social formats.",
    fields: [
      { name: "agent_name", label: "Agent Name", required: true },
      { name: "years", label: "Years in Real Estate" },
      { name: "specialty", label: "Specialty / Niche" },
      { name: "market", label: "Location / Market", required: true },
      { name: "designations", label: "License / Designations" },
      { name: "brokerage", label: "Brokerage" },
      { name: "background", label: "Personal Background", type: "textarea", rows: 3 },
      { name: "why", label: "Why They Got Into Real Estate", type: "textarea", rows: 2 },
      { name: "differentiators", label: "Unique Differentiators", type: "textarea", rows: 3 },
      { name: "interests", label: "Personal Interests", type: "textarea", rows: 2 },
      { name: "tone", label: "Tone", defaultValue: "Professional but approachable" },
    ],
  },
  {
    slug: "testimonial",
    path: "/re/testimonial",
    label: "Testimonial Polish",
    description: "Clean up client testimonials and extract pull quotes.",
    fields: [
      { name: "raw_testimonial", label: "Raw Testimonial", type: "textarea", rows: 6, required: true },
      { name: "client_name", label: "Client Name" },
      { name: "transaction_type", label: "Transaction Type" },
      { name: "theme", label: "Key Theme to Preserve" },
    ],
  },
  {
    slug: "referral",
    path: "/re/referral",
    label: "Referral Thank-You",
    description: "Write a referral thank-you email, letter, and gift suggestion.",
    fields: [
      { name: "source_name", label: "Referral Source Name", required: true },
      { name: "relationship", label: "Relationship to Agent" },
      { name: "referral_name", label: "Who They Referred" },
      { name: "outcome", label: "Outcome" },
      { name: "notes", label: "Anything Special", type: "textarea", rows: 3 },
    ],
  },
];

export const CONTRACT_MODULES = [
  {
    slug: "listing-agreement",
    path: "/contracts/listing-agreement",
    label: "Listing Agreement",
    description: "Draft listing agreement sections with fillable placeholders.",
    fields: [
      { name: "address", label: "Property Address", required: true },
      { name: "seller_names", label: "Seller Name(s)", required: true },
      { name: "start_date", label: "Listing Start Date", type: "date" },
      { name: "end_date", label: "Listing End Date", type: "date" },
      { name: "list_price", label: "Listing Price" },
      { name: "commission", label: "Commission Rate" },
      { name: "buyer_commission", label: "Buyer Agent Commission" },
      { name: "lockbox", label: "Lockbox", type: "select", options: [{ value: "Yes", label: "Yes" }, { value: "No", label: "No" }], defaultValue: "Yes" },
      { name: "mls_auth", label: "MLS Authorization", type: "select", options: [{ value: "Yes", label: "Yes" }, { value: "No", label: "No" }], defaultValue: "Yes" },
      { name: "special_terms", label: "Special Terms", type: "textarea", rows: 3 },
    ],
  },
  {
    slug: "buyer-broker",
    path: "/contracts/buyer-broker",
    label: "Buyer Broker Agreement",
    description: "Draft buyer broker agreement sections.",
    fields: [
      { name: "buyer_names", label: "Buyer Name(s)", required: true },
      { name: "start_date", label: "Agreement Start", type: "date" },
      { name: "end_date", label: "Agreement End", type: "date" },
      { name: "area", label: "Geographic Area" },
      { name: "property_type", label: "Property Type" },
      { name: "price_range", label: "Price Range" },
      { name: "compensation", label: "Compensation" },
      { name: "dual_agency", label: "Dual Agency Permitted", type: "select", options: [{ value: "No", label: "No" }, { value: "Yes", label: "Yes" }], defaultValue: "No" },
    ],
  },
];
