export const REAL_ESTATE_MODULES = [
  {
    slug: "neighborhood",
    path: "/re/neighborhood",
    label: "Neighborhood Report",
    description: "Create a client-facing neighborhood market report.",
    fields: [
      { name: "neighborhood", label: "Neighborhood / Area", required: true },
      { name: "location", label: "City / ZIP", required: true },
      { name: "property_type", label: "Property Type Focus", placeholder: "Single family residential" },
      { name: "price_range", label: "Price Range in Area", placeholder: "$500K-$700K" },
      { name: "agent_notes", label: "Agent Notes", type: "textarea", rows: 3 },
    ],
  },
  {
    slug: "rpr",
    path: "/re/rpr",
    label: "Full RPR Report",
    description: "Create a comprehensive RPR-style property resource report from listing, market, tax, HOA, and comparable data.",
    fields: [
      {
        name: "report_purpose",
        label: "Report Purpose",
        type: "select",
        defaultValue: "Buyer property review",
        options: [
          { value: "Buyer property review", label: "Buyer Property Review" },
          { value: "Seller listing prep", label: "Seller Listing Prep" },
          { value: "Listing presentation", label: "Listing Presentation" },
          { value: "Investor analysis", label: "Investor Analysis" },
          { value: "Relocation overview", label: "Relocation Overview" },
        ],
      },
      {
        name: "audience",
        label: "Audience",
        type: "select",
        defaultValue: "Client-facing",
        options: [
          { value: "Client-facing", label: "Client-Facing" },
          { value: "Agent internal", label: "Agent Internal" },
          { value: "Buyer", label: "Buyer" },
          { value: "Seller", label: "Seller" },
          { value: "Investor", label: "Investor" },
        ],
      },
      { name: "client_name", label: "Client Name", placeholder: "John and Mary Smith" },
      { name: "address", label: "Property Address", required: true, placeholder: "123 Main St, Austin, TX 78701" },
      { name: "city", label: "City", group: "location" },
      { name: "state", label: "State", group: "location" },
      { name: "zip_code", label: "ZIP", group: "location" },
      { name: "county", label: "County", group: "location" },
      { name: "property_type", label: "Property Type", placeholder: "Single family", group: "property" },
      { name: "property_style", label: "Style", placeholder: "Ranch, colonial, modern", group: "property" },
      { name: "condition", label: "Condition", placeholder: "Updated, original, renovated", group: "property" },
      { name: "garage", label: "Garage / Parking", placeholder: "2-car garage", group: "property" },
      { name: "bedrooms", label: "Bedrooms", type: "stepper", min: 0, max: 12, step: 1, group: "stats" },
      { name: "bathrooms", label: "Bathrooms", type: "stepper", min: 0, max: 10, step: 0.5, group: "stats" },
      { name: "sqft", label: "Sq Ft", type: "number", placeholder: "1850", group: "stats" },
      { name: "lot_size", label: "Lot Size", placeholder: "0.25 ac", group: "stats" },
      { name: "year_built", label: "Year Built", type: "number", placeholder: "2005", group: "stats" },
      { name: "features", label: "Key Features", type: "textarea", rows: 3, placeholder: "Updated kitchen, pool, screened porch, new HVAC..." },
      { name: "updates", label: "Recent Updates / Improvements", type: "textarea", rows: 3 },
      { name: "property_details", label: "Property Details", type: "textarea", rows: 3, placeholder: "Layout, room notes, lot orientation, condition details..." },
      { name: "current_price", label: "List / Current Price", placeholder: "$485,000", group: "pricing" },
      { name: "recommended_price", label: "Recommended Price", placeholder: "$475,000", group: "pricing" },
      { name: "value_range", label: "Value Range", placeholder: "$465,000 - $490,000", group: "pricing" },
      { name: "assessed_value", label: "Assessed Value", placeholder: "$410,000", group: "pricing" },
      { name: "annual_taxes", label: "Annual Taxes", placeholder: "$6,250", group: "pricing" },
      { name: "hoa", label: "HOA", placeholder: "Yes / No / Unknown", group: "hoa" },
      { name: "hoa_fee", label: "HOA Fee", placeholder: "$150/mo", group: "hoa" },
      { name: "hoa_covers", label: "HOA Covers", type: "textarea", rows: 2 },
      { name: "market_notes", label: "Market Notes", type: "textarea", rows: 3, placeholder: "Inventory, demand, price trends, buyer behavior..." },
      { name: "comparables", label: "Comparable Properties", type: "textarea", rows: 5, placeholder: "One comp per line with address, price, specs, sale/list date, DOM, and notes" },
      { name: "competitors", label: "Competing Active Listings", type: "textarea", rows: 4 },
      { name: "dom", label: "Days on Market", type: "number", group: "market" },
      { name: "showings", label: "Showings", type: "number", group: "market" },
      { name: "offers", label: "Offers", placeholder: "None, multiple, one pending", group: "market" },
      { name: "target_buyer", label: "Target Buyer", placeholder: "Move-up family, first-time buyer, investor", group: "market" },
      { name: "feedback", label: "Buyer Feedback", type: "textarea", rows: 3 },
      { name: "neighborhood", label: "Neighborhood / Location Notes", type: "textarea", rows: 3 },
      { name: "schools", label: "Schools", type: "textarea", rows: 2 },
      { name: "utilities", label: "Utilities", type: "textarea", rows: 2 },
      { name: "flood_zone", label: "Flood Zone", placeholder: "Unknown, X, AE..." },
      { name: "showing_instructions", label: "Showing Instructions", type: "textarea", rows: 2 },
      { name: "open_house", label: "Open House Info", type: "textarea", rows: 2 },
      { name: "closing_pref", label: "Closing Preference", type: "textarea", rows: 2 },
      { name: "inclusions", label: "Inclusions", type: "textarea", rows: 2 },
      { name: "exclusions", label: "Exclusions", type: "textarea", rows: 2 },
      { name: "notes", label: "Additional Notes", type: "textarea", rows: 3 },
    ],
  },
  {
    slug: "appointment",
    path: "/re/appointment",
    label: "Listing Appointment",
    description: "Build listing presentation talking points and objection responses.",
    fields: [
      { name: "address", label: "Property Address", required: true, placeholder: "e.g. 123 Oak Ave, Austin TX" },
      { name: "specs", label: "Bedrooms / Baths / Sqft", required: true, placeholder: "e.g. 4 beds, 3 baths, 2,500 sqft" },
      { name: "value_range", label: "Estimated Value Range", placeholder: "e.g. $450,000 - $480,000" },
      { name: "seller_situation", label: "Seller Situation", type: "textarea", rows: 2, placeholder: "e.g. Relocating for work, needs to sell within 60 days, highly motivated" },
      { name: "challenges", label: "Known Challenges", type: "textarea", rows: 2, placeholder: "e.g. Needs new roof, busy street traffic, dated kitchen" },
      { name: "notes", label: "Agent Notes", type: "textarea", rows: 3, placeholder: "e.g. Highlight nearby parks, mention strong local school ratings" },
    ],
  },
  {
    slug: "competitive",
    path: "/re/competitive",
    label: "Competitive Analysis",
    description: "Compare a subject listing against active competition.",
    fields: [
      { name: "address", label: "Subject Property", required: true, placeholder: "e.g. 123 Oak Ave, Austin TX" },
      { name: "specs", label: "Subject Specs", required: true, placeholder: "e.g. 4 beds, 3 baths, 2,500 sqft" },
      { name: "list_price", label: "List Price", placeholder: "e.g. $475,000" },
      { name: "features", label: "Key Features", type: "textarea", rows: 3, placeholder: "e.g. Fully remodeled kitchen, quartz countertops, swimming pool, oversized 2-car garage" },
      { name: "competitors", label: "Competing Active Listings", type: "textarea", rows: 5, placeholder: "e.g. 145 Oak Ave: $485,000, 4/2.5/2400, 12 DOM, updated kitchen\n110 Pine St: $460,000, 3/2/2100, 45 DOM, needs roof" },
      { name: "market_notes", label: "Market Context", type: "textarea", rows: 2, placeholder: "e.g. Seller's market with low inventory; average days on market is 14 days; homes selling at 99% of list price." },
    ],
  },
  {
    slug: "timeline",
    path: "/re/timeline",
    label: "Transaction Timeline",
    description: "Generate milestone emails for buyers or sellers under contract.",
    fields: [
      { name: "transaction_type", label: "Transaction Type", type: "select", options: [{ value: "purchase", label: "Purchase" }, { value: "sale", label: "Sale" }], defaultValue: "purchase" },
      { name: "client_type", label: "Client Type", type: "select", options: [{ value: "buyer", label: "Buyer" }, { value: "seller", label: "Seller" }], defaultValue: "buyer" },
      { name: "client_name", label: "Client Name", required: true },
      { name: "address", label: "Property Address", required: true },
      { name: "contract_date", label: "Contract Date", type: "date", hint: "Auto-fills common editable deadline defaults when selected." },
      { name: "inspection_end", label: "Inspection Period Ends", type: "date", hint: "Default: 10 calendar days after contract." },
      { name: "appraisal_date", label: "Appraisal Deadline", type: "date", hint: "Default: 21 calendar days after contract." },
      { name: "loan_commitment", label: "Loan Commitment", type: "date", hint: "Default: 25 calendar days after contract." },
      { name: "walkthrough_date", label: "Final Walkthrough", type: "date" },
      { name: "closing_disclosure_due", label: "Closing Disclosure Due", type: "date", hint: "Default: 3 CFPB business days before closing; adjust for holidays or local practice." },
      { name: "closing_date", label: "Closing Date", type: "date", required: true },
    ],
  },
  {
    slug: "seller-update",
    path: "/re/seller-update",
    label: "Seller Update",
    description: "Write a weekly listing update email for sellers.",
    fields: [
      { name: "seller_name", label: "Seller Name", required: true, placeholder: "e.g. John & Jane Doe" },
      { name: "address", label: "Property Address", required: true, placeholder: "e.g. 123 Oak Ave, Austin TX" },
      { name: "dom", label: "Days on Market", type: "number", placeholder: "e.g. 14" },
      { name: "week_number", label: "Week Number", placeholder: "e.g. Week 2" },
      { name: "showing_count", label: "Showings This Week", type: "number", placeholder: "e.g. 5" },
      { name: "feedback", label: "Buyer Feedback", type: "textarea", rows: 4, placeholder: "e.g. Property showed well. One buyer loved the backyard but thought the kitchen was a bit dark. Another buyer is comparing with a nearby listing." },
      { name: "price_discussion", label: "Price Discussion Needed", type: "select", options: [{ value: "No", label: "No" }, { value: "Yes", label: "Yes" }], defaultValue: "No" },
      { name: "market_notes", label: "Market Notes", type: "textarea", rows: 2, placeholder: "e.g. Two new active listings in the neighborhood this week; average sale price remains steady." },
      { name: "agent_actions", label: "Agent Action Items", type: "textarea", rows: 2, placeholder: "e.g. Follow up with open house visitors; run local Facebook ad campaign; review pricing strategy next Tuesday." },
    ],
  },
  {
    slug: "buyer-consult",
    path: "/re/buyer-consult",
    label: "Buyer Consultation",
    description: "Turn buyer consultation notes into a needs analysis.",
    fields: [
      { name: "buyer_names", label: "Buyer Name(s)", required: true, placeholder: "e.g. Michael & Sarah Johnson" },
      { name: "date", label: "Consultation Date", type: "date" },
      { name: "pre_approved", label: "Pre-Approved", type: "select", options: [{ value: "Unknown", label: "Unknown" }, { value: "Yes", label: "Yes" }, { value: "No", label: "No" }], defaultValue: "Unknown" },
      { name: "budget", label: "Budget Range", required: true, placeholder: "e.g. $550,000 - $600,000" },
      { name: "down_payment", label: "Down Payment", placeholder: "e.g. 20% ($110,000 - $120,000)" },
      { name: "target_areas", label: "Target Areas", type: "textarea", rows: 2, placeholder: "e.g. West Lake Hills, South Lamar, Cherrywood" },
      { name: "must_haves", label: "Must-Haves", type: "textarea", rows: 3, placeholder: "e.g. 3+ bedrooms, 2+ bathrooms, home office space, fenced backyard for dog" },
      { name: "nice_to_haves", label: "Nice-to-Haves", type: "textarea", rows: 2, placeholder: "e.g. Double vanity in master, covered patio, quiet cul-de-sac, hardwood floors" },
      { name: "deal_breakers", label: "Deal-Breakers", type: "textarea", rows: 2, placeholder: "e.g. Near highway noise, no garage, busy main road, HOA with rental restrictions" },
      { name: "timeline", label: "Timeline to Buy", placeholder: "e.g. Ready to buy immediately, lease ends in 3 months" },
      { name: "motivation", label: "Motivation", type: "textarea", rows: 2, placeholder: "e.g. Renting for too long, wants to build equity, expecting first child and needs more space" },
      { name: "current_situation", label: "Current Situation", type: "textarea", rows: 2, placeholder: "e.g. Currently renting a 2-bedroom apartment in downtown Austin" },
      { name: "agent_notes", label: "Private Agent Notes", type: "textarea", rows: 3, placeholder: "e.g. High focus on school districts. Sarah is a hybrid worker so home office is crucial. Mentioned pre-approval with local lender." },
    ],
  },
  {
    slug: "offer-letter",
    path: "/re/offer-letter",
    label: "Offer Letter",
    description: "Draft a personal buyer-to-seller letter.",
    fields: [
      { name: "buyer_names", label: "Buyer Name(s)", required: true, placeholder: "e.g. Michael and Sarah Johnson" },
      { name: "buyer_situation", label: "Buyer Situation", type: "textarea", rows: 2, placeholder: "e.g. Growing family of four relocating from Chicago. Pre-approved and ready to close quickly." },
      { name: "home_highlights", label: "What They Loved About the Home", type: "textarea", rows: 3, required: true, placeholder: "e.g. The open kitchen and backyard were perfect — their kids immediately ran to the yard. They loved the natural light and the quiet street." },
      { name: "buyer_story", label: "Buyer Story", type: "textarea", rows: 4, required: true, placeholder: "e.g. Michael is a teacher and Sarah is a nurse. They've been renting for 5 years while saving for their first home. This neighborhood is close to Sarah's hospital and the school their kids will attend." },
      {
        name: "tone",
        label: "Tone",
        type: "select",
        defaultValue: "Warm and sincere",
        options: [
          { value: "Warm and sincere", label: "Warm and Sincere" },
          { value: "Heartfelt and emotional", label: "Heartfelt and Emotional" },
          { value: "Professional and respectful", label: "Professional and Respectful" },
          { value: "Casual and conversational", label: "Casual and Conversational" },
          { value: "Concise and direct", label: "Concise and Direct" },
          { value: "Family-focused", label: "Family-Focused" },
          { value: "Grateful and humble", label: "Grateful and Humble" },
        ],
      },
      { name: "extra_details", label: "Additional Personal Details", type: "textarea", rows: 2, placeholder: "e.g. They have a golden retriever named Biscuit who they can already picture in the backyard. This is the first house they've seen that felt like home." },
    ],
  },
  {
    slug: "expired-outreach",
    path: "/re/expired-outreach",
    label: "Expired / FSBO",
    description: "Create a five-touch expired listing or FSBO outreach sequence.",
    fields: [
      { name: "lead_type", label: "Lead Type", type: "select", options: [{ value: "Expired listing", label: "Expired Listing" }, { value: "FSBO", label: "FSBO" }], defaultValue: "Expired listing" },
      { name: "owner_name", label: "Owner Name" },
      { name: "address", label: "Property Address", required: true },
      { name: "days", label: "Days Expired / FSBO" },
      { name: "original_price", label: "Original List Price" },
      { name: "reason", label: "Known Reason", type: "textarea", rows: 2 },
      { name: "differentiator", label: "Agent Differentiator", type: "textarea", rows: 2 },
    ],
  },
  {
    slug: "soi-campaign",
    path: "/re/soi-campaign",
    label: "SOI Campaign",
    description: "Generate relationship-focused sphere emails by segment.",
    fields: [
      { name: "segments", label: "Segments", type: "textarea", rows: 4, placeholder: "Past clients: homeowners from last 3 years\nReferral partners: lenders, attorneys" },
      { name: "context", label: "Season / Context" },
      { name: "value_offer", label: "Value to Offer" },
      { name: "cta", label: "Call to Action" },
    ],
  },
  {
    slug: "just-listed",
    path: "/re/just-listed",
    label: "Just Listed / Sold",
    description: "Create a full announcement suite for a listing or sale.",
    fields: [
      { name: "announcement_type", label: "Announcement Type", type: "select", options: [{ value: "Just Listed", label: "Just Listed" }, { value: "Just Sold", label: "Just Sold" }], defaultValue: "Just Listed" },
      { name: "address", label: "Property Address", required: true },
      { name: "price", label: "Price" },
      { name: "specs", label: "Key Stats" },
      { name: "headline_feature", label: "Headline Feature" },
      { name: "ig_handle", label: "Instagram Handle" },
      { name: "open_house", label: "Open House Info" },
    ],
  },
  {
    slug: "open-house-followup",
    path: "/re/open-house-followup",
    label: "Open House Follow-Up",
    description: "Write personalized follow-up emails for open house visitors.",
    fields: [
      { name: "address", label: "Property Address", required: true },
      { name: "date", label: "Open House Date", type: "date" },
      { name: "visitors", label: "Visitors and Notes", type: "textarea", rows: 6, placeholder: "Jane, jane@email.com: liked kitchen, worried about commute" },
    ],
  },
  {
    slug: "virtual-staging",
    path: "/re/virtual-staging",
    label: "Virtual Staging Plan",
    description: "Create room-by-room staging recommendations and buyer vision copy.",
    fields: [
      { name: "address", label: "Property Address", required: true },
      {
        name: "style",
        label: "Property Style",
        type: "combobox",
        options: [
          { value: "Modern", label: "Modern" },
          { value: "Contemporary", label: "Contemporary" },
          { value: "Mid-Century Modern", label: "Mid-Century Modern" },
          { value: "Traditional", label: "Traditional" },
          { value: "Craftsman", label: "Craftsman" },
          { value: "Victorian", label: "Victorian" },
          { value: "Colonial", label: "Colonial" },
          { value: "Mediterranean", label: "Mediterranean" },
          { value: "Ranch", label: "Ranch" },
          { value: "Farmhouse", label: "Farmhouse" },
          { value: "Modern Farmhouse", label: "Modern Farmhouse" },
          { value: "Industrial", label: "Industrial" },
          { value: "Rustic", label: "Rustic" },
        ],
      },
      { name: "target_buyer", label: "Target Buyer" },
      { name: "price", label: "Price Point" },
      { name: "rooms", label: "Rooms", type: "textarea", rows: 6, required: true, placeholder: "Living room: 18x20, empty, fireplace\nPrimary bedroom: needs warmth" },
    ],
  },
  {
    slug: "property-faq",
    path: "/re/property-faq",
    label: "Property FAQ",
    description: "Generate a showing and open house FAQ document.",
    fields: [
      { name: "address", label: "Property Address", required: true, placeholder: "e.g. 123 Oak Ave, Austin TX" },
      { name: "property_details", label: "Property Details", type: "textarea", rows: 4, placeholder: "e.g. 4 bedrooms, 3 bathrooms, 2,500 sqft, built in 2015, two-story craftsman style home with private backyard." },
      { name: "hoa", label: "HOA", placeholder: "e.g. Oak Ridge Homeowners Association" },
      { name: "hoa_fee", label: "HOA Monthly Fee", placeholder: "e.g. $150 / month" },
      { name: "hoa_covers", label: "What HOA Covers", placeholder: "e.g. Community pool access, front yard landscaping, trash pickup" },
      { name: "schools", label: "School District", placeholder: "e.g. Eanes ISD: Oak Elementary, West Ridge Middle, Westlake High" },
      { name: "flood_zone", label: "Flood Zone", placeholder: "e.g. Zone X (unshaded) - minimal risk" },
      { name: "utilities", label: "Utilities", placeholder: "e.g. City of Austin Water, Austin Energy (Electricity), Texas Gas Service" },
      { name: "updates", label: "Recent Updates", type: "textarea", rows: 2, placeholder: "e.g. New HVAC unit (2024), kitchen remodel with quartz countertops (2023), water heater replaced (2022)" },
      { name: "closing_pref", label: "Seller Closing Timeline", placeholder: "e.g. Flexible, prefers 30-45 day close with optional 2-week leaseback" },
      { name: "inclusions", label: "Inclusions", placeholder: "e.g. All kitchen appliances, washer and dryer, backyard storage shed" },
      { name: "exclusions", label: "Exclusions", placeholder: "e.g. Living room wall-mounted TV, mounted security cameras, dining room chandelier" },
      { name: "showing_instructions", label: "Showing Instructions", placeholder: "e.g. Showings allowed daily 9am - 8pm via SentriLock. Please provide 2 hours notice; seller has a friendly dog." },
      { name: "notes", label: "Additional Notes", type: "textarea", rows: 2, placeholder: "e.g. Survey available in documents folder. House has a transferrable roof warranty." },
    ],
  },
  {
    slug: "price-reduction",
    path: "/re/price-reduction",
    label: "Price Reduction",
    description: "Prepare a data-informed price reduction recommendation memo.",
    fields: [
      { name: "seller_name", label: "Seller Name", required: true, placeholder: "e.g. John & Jane Doe" },
      { name: "address", label: "Property Address", required: true, placeholder: "e.g. 123 Oak Ave, Austin TX" },
      { name: "current_price", label: "Current List Price", required: true, placeholder: "e.g. $495,000" },
      { name: "dom", label: "Days on Market", type: "number", placeholder: "e.g. 45" },
      { name: "showings", label: "Showings to Date", type: "number", placeholder: "e.g. 12" },
      { name: "offers", label: "Offers Received", placeholder: "e.g. 0" },
      { name: "feedback", label: "Buyer Feedback Themes", type: "textarea", rows: 4, placeholder: "e.g. Consistent feedback that the home is beautiful but priced slightly high compared to recent neighborhood sales. Some buyers noted the backyard requires landscaping." },
      { name: "recommended_price", label: "Recommended New Price", placeholder: "e.g. $475,000" },
      { name: "competition", label: "Competing Listings", type: "textarea", rows: 3, placeholder: "e.g. 145 Oak Ave recently reduced to $480,000; 110 Pine St listed at $465,000 under contract in 8 days." },
      { name: "market_trend", label: "Market Trend", placeholder: "e.g. Slower spring market, inventory up 15%, average days on market increasing to 30 days." },
    ],
  },
  {
    slug: "business-plan",
    path: "/re/business-plan",
    label: "Business Plan",
    description: "Build an annual agent business plan and review.",
    fields: [
      { name: "agent_name", label: "Agent Name", required: true },
      { name: "years", label: "Years in Business" },
      { name: "last_closings", label: "Last Year Closings", type: "number" },
      { name: "last_gci", label: "Last Year GCI" },
      { name: "lead_sources", label: "Top Lead Sources", type: "textarea", rows: 2 },
      { name: "goal_closings", label: "Goal Closings Next Year", type: "number" },
      { name: "goal_gci", label: "Goal GCI Next Year" },
      { name: "avg_commission", label: "Average Commission" },
      { name: "team_size", label: "Team Size" },
      { name: "challenge", label: "Biggest Challenge Last Year", type: "textarea", rows: 2 },
      { name: "focus", label: "Focus Area for Growth", type: "textarea", rows: 2 },
    ],
  },
  {
    slug: "bio",
    path: "/re/bio",
    label: "Agent Bio",
    description: "Write agent bios in long, short, and social formats.",
    fields: [
      { name: "agent_name", label: "Agent Name", required: true },
      { name: "years", label: "Years in Real Estate" },
      { name: "specialty", label: "Specialty / Niche" },
      { name: "market", label: "Location / Market", required: true },
      { name: "designations", label: "License / Designations" },
      { name: "brokerage", label: "Brokerage" },
      { name: "background", label: "Personal Background", type: "textarea", rows: 3 },
      { name: "why", label: "Why They Got Into Real Estate", type: "textarea", rows: 2 },
      { name: "differentiators", label: "Unique Differentiators", type: "textarea", rows: 3 },
      { name: "interests", label: "Personal Interests", type: "textarea", rows: 2 },
      { name: "tone", label: "Tone", defaultValue: "Professional but approachable" },
    ],
  },
  {
    slug: "testimonial",
    path: "/re/testimonial",
    label: "Testimonial Polish",
    description: "Clean up client testimonials and extract pull quotes.",
    fields: [
      { name: "raw_testimonial", label: "Raw Testimonial", type: "textarea", rows: 6, required: true },
      { name: "client_name", label: "Client Name" },
      { name: "transaction_type", label: "Transaction Type" },
      { name: "theme", label: "Key Theme to Preserve" },
    ],
  },
  {
    slug: "referral",
    path: "/re/referral",
    label: "Referral Thank-You",
    description: "Write a referral thank-you email, letter, and gift suggestion.",
    fields: [
      { name: "source_name", label: "Referral Source Name", required: true },
      { name: "relationship", label: "Relationship to Agent" },
      { name: "referral_name", label: "Who They Referred" },
      { name: "outcome", label: "Outcome" },
      { name: "notes", label: "Anything Special", type: "textarea", rows: 3 },
    ],
  },
];

export const CONTRACT_MODULES = [
  {
    slug: "listing-agreement",
    path: "/contracts/listing-agreement",
    label: "Listing Agreement",
    description: "Draft listing agreement sections with fillable placeholders.",
    fields: [
      { name: "address", label: "Property Address", required: true },
      { name: "seller_names", label: "Seller Name(s)", required: true },
      { name: "start_date", label: "Listing Start Date", type: "date" },
      { name: "end_date", label: "Listing End Date", type: "date" },
      { name: "list_price", label: "Listing Price" },
      { name: "commission", label: "Commission Rate" },
      { name: "buyer_commission", label: "Buyer Agent Commission" },
      { name: "lockbox", label: "Lockbox", type: "select", options: [{ value: "Yes", label: "Yes" }, { value: "No", label: "No" }], defaultValue: "Yes" },
      { name: "mls_auth", label: "MLS Authorization", type: "select", options: [{ value: "Yes", label: "Yes" }, { value: "No", label: "No" }], defaultValue: "Yes" },
      { name: "special_terms", label: "Special Terms", type: "textarea", rows: 3 },
    ],
  },
  {
    slug: "buyer-broker",
    path: "/contracts/buyer-broker",
    label: "Buyer Broker Agreement",
    description: "Draft buyer broker agreement sections.",
    fields: [
      { name: "buyer_names", label: "Buyer Name(s)", required: true },
      { name: "start_date", label: "Agreement Start", type: "date" },
      { name: "end_date", label: "Agreement End", type: "date" },
      { name: "area", label: "Geographic Area" },
      { name: "property_type", label: "Property Type" },
      { name: "price_range", label: "Price Range" },
      { name: "compensation", label: "Compensation" },
      { name: "dual_agency", label: "Dual Agency Permitted", type: "select", options: [{ value: "No", label: "No" }, { value: "Yes", label: "Yes" }], defaultValue: "No" },
    ],
  },
];
